-- Adicciones
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Adicción a los Videojuegos: Identificación y Estrategias de Intervención', 'Adicciones', 'Explora cómo los psicólogos pueden ayudar a los individuos a manejar el uso problemático de los videojuegos, incluyendo consejos para padres y educadores.', 'https://images.pexels.com/photos/7047356/pexels-photo-7047356.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Adicción al Trabajo: Cómo Reconocer y Tratar la Necesidad Compulsiva de Trabajar', 'Adicciones', 'Examina los efectos negativos del trabajo compulsivo en la salud mental y ofrece estrategias para fomentar un equilibrio saludable entre el trabajo y la vida personal.', 'https://images.pexels.com/photos/1595385/pexels-photo-1595385.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Adicción al Alcohol: Estrategias de Intervención y Apoyo Familiar', 'Adicciones', 'Examina cómo afecta el alcoholismo a individuos y familias, y ofrece consejos sobre cómo los psicólogos pueden ayudar tanto a los pacientes como a sus seres queridos.', 'https://images.pexels.com/photos/8253559/pexels-photo-8253559.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Prevención y Tratamiento de la Adicción a las Drogas Recreativas', 'Adicciones', 'Discute las diversas formas en que los psicólogos pueden abordar la adicción a las drogas recreativas, incluyendo terapias de grupo, terapia cognitivo-conductual y programas de mantenimiento con metadona.', 'https://images.pexels.com/photos/360622/pexels-photo-360622.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Neurociencia de las Adicciones: Descubrimientos Recientes y Su Impacto en el Tratamiento', 'Adicciones', 'Revisa estudios científicos recientes sobre cómo las adicciones afectan el cerebro y discute cómo este conocimiento puede mejorar los enfoques terapéuticos.', 'https://images.pexels.com/photos/8088495/pexels-photo-8088495.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '5');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
VALUES ('Terapias Innovadoras para la Adicción: Enfoques Prometedores y Resultados Esperados', 'Adicciones', 'Explora nuevas terapias y tecnologías que están siendo utilizadas por psicólogos para tratar las adicciones, como la realidad virtual y la terapia de exposición.', 'https://images.pexels.com/photos/965879/pexels-photo-965879.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');

-- Ansiedad
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
 VALUES ('Técnicas de Respiración y Relajación para Reducir la Ansiedad', 'Ansiedad', 'Ofrece ejercicios prácticos de respiración y técnicas de relajación que los individuos pueden usar para reducir los síntomas de ansiedad en situaciones cotidianas.', 'https://images.pexels.com/photos/775417/pexels-photo-775417.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
 VALUES ('Ansiedad Social: Estrategias para Superar el Miedo a la Interacción Social', 'Ansiedad', 'Explora cómo los psicólogos pueden ayudar a las personas a enfrentar y superar la ansiedad social, proporcionando consejos prácticos y ejemplos de técnicas de exposición gradual.', 'https://images.pexels.com/photos/7149144/pexels-photo-7149144.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');

INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
 VALUES ('Ansiedad Infantil: Cómo Identificar y Apoyar a Niños con Ansiedad', 'Ansiedad', 'Ofrece orientación a padres y cuidadores sobre cómo reconocer los signos de ansiedad en niños y proporcionar apoyo emocional y estrategias de manejo adecuadas a su edad.', 'https://images.pexels.com/photos/4474035/pexels-photo-4474035.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');

 INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)
 VALUES ('Intervenciones Digitales para la Ansiedad: Aplicaciones y Eficacia', 'Ansiedad', 'Explora el uso de aplicaciones móviles y herramientas digitales para ayudar a las personas a manejar la ansiedad, evaluando su eficacia y beneficios potenciales.', 'https://images.pexels.com/photos/267389/pexels-photo-267389.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Atención
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('¿Qué es la Atención y por qué es Importante?', 'Atención', 'Explora los conceptos básicos de la atención, cómo se define en psicología y su papel crucial en el procesamiento de la información y el comportamiento humano.', 'https://images.pexels.com/photos/39080/stop-shield-traffic-sign-road-sign-39080.jpeg?auto=compress&cs=tinysrgb&w=600', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Trastorno por Déficit de Atención e Hiperactividad (TDAH): Mitos y Realidades', 'Atención', 'Aborda los conceptos erróneos comunes sobre el TDAH, discute los síntomas clave y ofrece estrategias efectivas de manejo y tratamiento.', 'https://images.pexels.com/photos/3856026/pexels-photo-3856026.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Técnicas y Ejercicios para Mejorar la Concentración', 'Atención', 'Proporciona consejos prácticos y ejercicios que pueden ayudar a las personas a desarrollar habilidades para mejorar su capacidad de concentración y atención.', 'https://images.pexels.com/photos/8436715/pexels-photo-8436715.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('La Importancia del Entorno y las Rutinas en la Atención', 'Atención', 'Explora cómo el diseño del entorno y establecer rutinas consistentes pueden facilitar un mejor enfoque y atención en el trabajo, la escuela y la vida diaria.', 'https://images.pexels.com/photos/2545122/pexels-photo-2545122.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Autoestima
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Qué es la Autoestima y Cómo se Desarrolla', 'Autoestima', 'Este artículo explora el concepto de autoestima, desde su definición hasta cómo se desarrolla a lo largo de la vida. Descubre la importancia de una autoestima saludable para el bienestar emocional y aprende cómo influencias como la genética, las experiencias personales y el entorno social moldean nuestra percepción de nosotros mismos.', 'https://images.pexels.com/photos/6238119/pexels-photo-6238119.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Técnicas y Ejercicios para Aumentar la Autoestima', 'Autoestima', 'Descubre técnicas prácticas y ejercicios efectivos diseñados para fortalecer tu autoestima. Este artículo proporciona herramientas que puedes aplicar en tu vida diaria para cultivar una imagen más positiva de ti mismo y mejorar tu bienestar emocional.', 'https://images.pexels.com/photos/6156939/pexels-photo-6156939.jpeg?auto=compress&cs=tinysrgb&w=600', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Autoestima en Adolescentes: Construyendo una Autoimagen Positiva', 'Autoestima', 'Para padres y educadores, este artículo ofrece estrategias clave para apoyar a los adolescentes en el desarrollo de una autoestima saludable. Explora cómo influir positivamente durante períodos de cambio y crecimiento personal para fomentar una autoimagen positiva y duradera.', 'https://images.pexels.com/photos/22820148/pexels-photo-22820148/free-photo-of-edificio-jugando-colegio-escuela.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Psicología Positiva y Autoestima: Enfoques Contemporáneos y Prácticas Recomendadas', 'Autoestima', 'Sumérgete en la psicología positiva y su relación con la autoestima. Este artículo revisa estudios recientes y prácticas efectivas que promueven el bienestar emocional y el desarrollo de una autoestima robusta a través de enfoques basados en la evidencia científica.', 'https://images.pexels.com/photos/7176224/pexels-photo-7176224.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- 	Crianza
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Principios Básicos de la Crianza Positiva', 'Crianza', 'Explora los principios fundamentales de la crianza positiva, incluyendo el establecimiento de límites efectivos, el fomento de la autonomía y la construcción de relaciones familiares saludables.', 'https://images.pexels.com/photos/4145354/pexels-photo-4145354.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Importancia del Vínculo Afectivo entre Padres e Hijos', 'Crianza', 'Examina cómo desarrollar y fortalecer el vínculo emocional entre padres e hijos desde una edad temprana y cómo este vínculo influye en el desarrollo emocional y social del niño.', 'https://images.pexels.com/photos/4148842/pexels-photo-4148842.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Técnicas de Disciplina Positiva: Alternativas al Castigo', 'Crianza', 'Ofrece consejos prácticos y ejemplos de técnicas de disciplina positiva que promueven el aprendizaje y la responsabilidad en lugar de enfocarse en castigos.', 'https://images.pexels.com/photos/3759660/pexels-photo-3759660.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Cómo Manejar los Berrinches y Conductas Desafiantes en Niños Pequeños', 'Crianza', 'Ofrece técnicas efectivas para manejar berrinches y comportamientos desafiantes, ayudando a los padres a mantener la calma y establecer límites de manera consistente.', 'https://images.pexels.com/photos/61129/pexels-photo-61129.jpeg?auto=compress&cs=tinysrgb&w=600', '4');

-- Ira
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('¿Qué es la Ira y por qué Surge?', 'Ira', 'Explora qué es la ira, cómo se manifiesta emocional y físicamente, y cuáles son las causas subyacentes comunes que pueden desencadenarla en las personas.', 'https://images.pexels.com/photos/12169057/pexels-photo-12169057.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Tipos de Ira: Diferencias entre Ira Constructiva y Destructiva', 'Ira', 'Discute las diferencias entre la ira constructiva, que puede canalizarse de manera positiva, y la ira destructiva, que puede tener consecuencias negativas para la salud mental y las relaciones interpersonales.', 'https://images.pexels.com/photos/3281130/pexels-photo-3281130.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Técnicas de Control de la Ira: Métodos para Calmar la Mente y el Cuerpo', 'Ira', 'Ofrece técnicas prácticas y ejercicios que las personas pueden usar para manejar eficazmente la ira, incluyendo la respiración profunda, la visualización calmante y la comunicación asertiva', 'https://images.pexels.com/photos/5598284/pexels-photo-5598284.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Efectos Negativos de la Ira no Controlada en la Salud Mental y Física', 'Ira', 'Examina cómo la ira crónica o mal gestionada puede afectar la salud mental y física a largo plazo, incluyendo el estrés, la ansiedad y problemas de salud cardiovascular.', 'https://images.pexels.com/photos/2401828/pexels-photo-2401828.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Depresión
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('¿Qué es la Depresión? Síntomas, Causas y Tipos', 'Depresión', 'Explora la definición clínica de la depresión, los diferentes tipos de trastornos depresivos y cómo se diagnostican. Discute los síntomas comunes y las posibles causas subyacentes, como factores genéticos, biológicos y ambientales.', 'https://images.pexels.com/photos/236151/pexels-photo-236151.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Depresión versus Tristeza: Diferencias y Cómo Reconocerlas', 'Depresión', 'Ayuda a los lectores a distinguir entre sentirse triste ocasionalmente y experimentar un trastorno depresivo clínico, proporcionando pautas claras sobre cuándo buscar ayuda profesional.', 'https://images.pexels.com/photos/636164/pexels-photo-636164.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Tratamientos Efectivos para la Depresión: Terapia, Medicación y Alternativas', 'Depresión', 'Explora las opciones de tratamiento disponibles, incluyendo terapia cognitivo-conductual, antidepresivos y terapias complementarias como el ejercicio físico y la meditación.', 'https://images.pexels.com/photos/2753486/pexels-photo-2753486.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Autoayuda y Estrategias Personales para Combatir la Depresión', 'Depresión', 'Proporciona consejos prácticos y estrategias que las personas pueden implementar por sí mismas para manejar los síntomas depresivos, como establecer rutinas diarias, practicar el autocuidado y buscar apoyo social.', 'https://images.pexels.com/photos/6238174/pexels-photo-6238174.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Estrés
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('¿Qué es el Estrés? Tipos, Causas y Síntomas', 'Estrés', 'Explora qué es el estrés, los diferentes tipos (agudo, crónico, laboral, etc.), sus causas comunes y cómo se manifiesta tanto física como emocionalmente.', 'https://images.pexels.com/photos/5542968/pexels-photo-5542968.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('La Ciencia del Estrés: Cómo Afecta tu Cuerpo y Mente', 'Estrés', 'Examina los efectos del estrés en el cerebro y el cuerpo, incluyendo la respuesta de lucha o huida y el impacto a largo plazo en la salud física y mental.', 'https://images.pexels.com/photos/22724091/pexels-photo-22724091/free-photo-of-punto-de-referencia-lago-larga-exposicion-reflejo.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Técnicas de Relajación para Reducir el Estrés', 'Estrés', 'Proporciona una variedad de técnicas de relajación, como la meditación, la respiración profunda y el yoga, que pueden ayudar a reducir el estrés y promover el bienestar general.', 'https://images.pexels.com/photos/339620/pexels-photo-339620.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Mindfulness y Estrés: Cómo Vivir en el Presente Puede Ayudar', 'Estrés', 'Explora cómo la práctica del mindfulness puede ayudar a las personas a manejar el estrés al enfocarse en el momento presente y reducir la reactividad emocional.', 'https://images.pexels.com/photos/5699864/pexels-photo-5699864.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Enfermedades Cronicas
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Cómo Hablar con tu Médico sobre tu Enfermedad Crónica', 'Enfermedades Cronicas', 'Ofrece consejos sobre cómo los pacientes pueden comunicarse de manera efectiva con sus médicos para asegurarse de recibir la mejor atención posible, incluyendo la preparación para las citas y la formulación de preguntas adecuadas.', 'https://images.pexels.com/photos/6303652/pexels-photo-6303652.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Recursos en Línea para Pacientes con Enfermedades Crónicas', 'Enfermedades Cronicas', 'Proporciona una lista de recursos en línea, incluyendo sitios web, aplicaciones móviles y grupos de apoyo virtuales que pueden ayudar a los pacientes a manejar sus enfermedades crónicas de manera más efectiva.', 'https://images.pexels.com/photos/18530593/pexels-photo-18530593/free-photo-of-gente-esperando-linea-hospital.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Trabajo y Enfermedades Crónicas: Cómo Mantener el Equilibrio', 'Enfermedades Cronicas', 'Ofrece estrategias para manejar una enfermedad crónica mientras se mantiene un empleo, incluyendo la importancia de la comunicación con el empleador y el establecimiento de límites saludables.', 'https://images.pexels.com/photos/4348401/pexels-photo-4348401.jpeg?auto=compress&cs=tinysrgb&w=600', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('La Importancia del Apoyo Social en el Manejo de Enfermedades Crónicas', 'Enfermedades Cronicas', 'Explora cómo el apoyo de familiares, amigos y grupos de apoyo puede ayudar a las personas a enfrentar mejor los desafíos asociados con las enfermedades crónicas y mejorar su bienestar emocional.', 'https://images.pexels.com/photos/4101143/pexels-photo-4101143.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- Impulsividad
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('¿Qué es la Impulsividad? Definición y Causas', 'Impulsividad', 'Explora la definición de la impulsividad, las causas subyacentes y cómo se manifiesta en diferentes contextos, desde la toma de decisiones rápidas hasta las acciones sin consideración de las consecuencias.', 'https://images.pexels.com/photos/7108245/pexels-photo-7108245.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Impulsividad y el Cerebro: La Ciencia detrás de las Decisiones Impulsivas', 'Impulsividad', 'Examina los mecanismos neurobiológicos involucrados en la impulsividad, incluyendo el papel de las regiones cerebrales como la corteza prefrontal y el sistema límbico.', 'https://images.pexels.com/photos/17483868/pexels-photo-17483868/free-photo-of-abstracto-resumen-tecnologia-investigacion.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Consecuencias de la Impulsividad en la Vida Diaria', 'Impulsividad', 'Discute cómo la impulsividad puede afectar diversos aspectos de la vida, incluyendo las relaciones interpersonales, el rendimiento académico y profesional, y la salud física y mental.', 'https://images.pexels.com/photos/14868803/pexels-photo-14868803.jpeg?auto=compress&cs=tinysrgb&w=600', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Estrategias Prácticas para Controlar la Impulsividad', 'Impulsividad', 'Proporciona consejos y técnicas prácticas para ayudar a las personas a manejar la impulsividad, incluyendo la práctica de la atención plena, el establecimiento de metas y el uso de técnicas de autocontrol.', 'https://images.pexels.com/photos/6455687/pexels-photo-6455687.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');

-- -- Top
-- INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('', 'Top', '', '', '1');
-- INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('', 'Top', '', '', '2');
-- INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('', 'Top', '', '', '3');
-- INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('', 'Top', '', '', '4');


-- Terapia de Pareja
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Cuándo Considerar la Terapia de Pareja: Señales y Beneficios', 'Terapia de Pareja', 'Explora las señales que indican que una pareja podría beneficiarse de la terapia, como problemas de comunicación, conflictos frecuentes y pérdida de intimidad. También discute los beneficios potenciales de buscar ayuda profesional.', 'https://images.pexels.com/photos/3958379/pexels-photo-3958379.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '1');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Principales Técnicas Utilizadas en la Terapia de Pareja', 'Terapia de Pareja', 'Proporciona una visión general de las técnicas comunes en la terapia de pareja, como la terapia cognitivo-conductual, la terapia centrada en las emociones y la terapia de comunicación.', 'https://images.pexels.com/photos/3760067/pexels-photo-3760067.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '2');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Recuperación de la Confianza y la Intimidad en la Relación', 'Terapia de Pareja', 'Examina cómo la terapia de pareja puede ayudar a las parejas a reconstruir la confianza y la intimidad después de eventos traumáticos como la infidelidad o la traición.', 'https://images.pexels.com/photos/4672717/pexels-photo-4672717.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '3');
INSERT INTO `posts` (`tema`, `especialidad`, `descripcion`, `imagen`, `psicologo_id`)  VALUES ('Cómo Elegir el Terapeuta de Pareja Adecuado para Ustedes', 'Terapia de Pareja', 'Proporciona consejos sobre qué buscar al elegir un terapeuta de pareja, incluyendo las credenciales, el enfoque terapéutico y la compatibilidad con las necesidades de la pareja.', 'https://images.pexels.com/photos/5336965/pexels-photo-5336965.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', '4');
